inherit_from:
  - https://raw.githubusercontent.com/decidim/decidim/release/0.30-stable/.rubocop.yml

AllCops:
  Exclude:
    - "spec/decidim_dummy_app*/**/*"
    - "development_app/**/*"

RSpec/DescribeClass:
  Exclude:
    - spec/i18n_spec.rb
    - "spec/system/**/*"
