services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dokploy
      args:
        DECIDIM_VERSION: 0.31.5
    environment:
      - PORT=3000
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@pg:5432/postgres
      - REDIS_URL=redis://redis:6379/0
    command: bundle exec rails server -b 0.0.0.0 -p 3000
  pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis