import "src/decidim/decidim_awesome/admin/constraints"
import "src/decidim/decidim_awesome/editors/quill_editor"
import "src/decidim/decidim_awesome/admin/form_builder"
import "src/decidim/decidim_awesome/editors/tabs_focus"
import "src/decidim/decidim_awesome/admin/codemirror"
import "src/decidim/decidim_awesome/admin/user_picker"
import "src/decidim/decidim_awesome/admin/auto_edit"
