import "src/decidim/decidim_awesome/admin/tabs_change"
import "src/decidim/decidim_awesome/admin/verifications"
import "src/decidim/decidim_awesome/admin/voting_cards_settings"
import "src/decidim/decidim_awesome/admin/awesome_processes_form"
import "src/decidim/decidim_awesome/admin/rich_text_columns_form"
