name: "[CI] Tests 0.26"

on:
  push:
    branches:
      - main
  pull_request:

env:
  CI: 1
  SIMPLECOV: 1
  NODE_VERSION: 16.9.1
  RUBY_VERSION: 2.7.7
  BUNDLE_GEMFILE: Gemfile.legacy

jobs:
  tests-legacy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rspec: awesome_summary_spec.rb
            features: disabled
          - rspec: " --exclude-pattern 'spec/system/**/*_spec.rb'"
            features: enabled
          - rspec: system/admin
            features: enabled
          - rspec: system/*_spec.rb
            features: enabled
          - rspec: system/awesome_map
            features: enabled
      fail-fast: false

    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Test App
        run: bundle exec rake test_app

      - name: General RSpec with config vars ${{ matrix.features }}
        run: bundle exec rspec spec/${{ matrix.rspec }}
        env:
          FEATURES: ${{ matrix.features }} 

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: ./spec/decidim_dummy_app/tmp/screenshots
